config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'products#index'

  resources :products do
    resources :reviews, only: [:create, :destroy]
  end

  resources :categories
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products

  validates :name, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :reviews, -> { order "created_at DESC" }

  validates :title, :description, presence: true

  mount_uploader :image, ImageUploader

  private

  def self.sortable(category_id)
    if category_id
      where(category_id: category_id)
    else
      all.order('created_at DESC')
    end
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  belongs_to :user

  validates :msg, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  responders :location, :flash
  respond_to :html

  protected

  def require_admin
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin

  expose :category
  expose :categories, ->{ Category.all }

  def create
    category.save
    respond_with category, location: -> { edit_category_path(category) }
  end

  def update
    category.save
    respond_with category, location: -> { category_path(category) }
  end

  def destroy
    category.destroy
    respond_with category, location: -> { root_path }
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :require_admin, only: [:update, :edit, :new, :create]

  expose :products,-> { Product.sortable(params[:category]) }
  expose :categories, -> { Category.all }
  expose :reviews,-> { product.reviews }
  expose :product
  expose :review

  def show
    self.review = product.reviews.build
  end

  def create
    product.save
    respond_with product, location: -> { product_path(product) }
  end

  def update
    product.save
    respond_with product, location: -> { product_path(product) }
  end

  def destroy
    product.destroy
    respond_with product, location: -> { root_path }
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :image, :category_id, :products_path)
  end

  def require_admin
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  expose :product, -> { Product.find(params[:product_id]) }
  expose :review
  expose :categories, -> {Category.all}
  expose :reviews, -> { product.reviews }

  def create
    if review.save
      redirect_to product
    else
      render "products/show"
    end
  end

  def destroy
    review.destroy
    respond_with review, location: -> { product_path(product) }
  end

  private

  def review_params
    params.require(:review).permit(:msg).merge!(user: current_user).merge!(product_id: product.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.slim
= bootstrap_form_for category do |f|
  = f.text_field :name
  = f.submit

app/views/categories/edit.html.slim
= render 'form'

= link_to 'Delete', category_path(category), method: :delete, data: { confirm: 'A u sure?' },
          class: 'btn-mini btn-danger'

app/views/categories/new.html.slim
= render 'form'

app/views/layouts/application.html.slim
doctype html

head
= csrf_meta_tags

= stylesheet_link_tag 'application', media: 'all'

body
  nav.navbar.navbar-default.navbar-static-top
    .container
      .row
        .col-md-8
          - if user_signed_in? && current_user.admin?
            = render 'partials/admin_tools'
        .col-md-4
          = render 'partials/rigester'
  .container
    .row
      .col-md-3
        p.lead Shop Name
        .list-group
          = render 'partials/sidebar' unless devise_controller?
      .col-md-9
        = render 'partials/messages'
        = yield
  .container
    hr
    /! Footer
    footer
      .row
        .col-lg-12
          p Copyright &copy; Your Website 2019


= javascript_include_tag 'application'

app/views/partials/_admin_tools.html.slim
= link_to 'New product', new_product_path, class: 'btn-mini btn-primary'
| |
= link_to 'New category', new_category_path, class: 'btn-mini btn-primary'

app/views/partials/_messages.html.slim
- flash.each do |name, msg|
  div(class="alert alert-#{name}")
    a.close(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/partials/_rigester.html.slim
.pull-right
  - if user_signed_in?
    | Logged in as #{current_user.email}
    = link_to 'Edit profile', edit_user_registration_path, class: 'btn-mini btn-primary'
    |
    = link_to "Logout", destroy_user_session_path, method: :delete, class: 'navbar-link'
  - else
    = link_to "Login", new_user_session_path, class: 'navbar-link'
    | |
    = link_to "Sign up", new_user_registration_path, class:'navbar-link'

app/views/partials/_sidebar.html.slim
ul.list-unstyled.ui-sortable
  li= link_to 'All', root_path
  - categories.each do |category|
    li
      = link_to category.name, root_path(category: category)
      - if user_signed_in? && current_user.admin?
        = link_to 'edit', edit_category_path(category), class: 'btn-mini btn-primary'

app/views/products/_form.html.slim
= bootstrap_form_for product do |f|
  = f.text_field :title
  = f.text_area :description
  = f.collection_select :category_id, Category.order(:name), :id, :name
  = f.file_field :image, label: "Image"
  = f.submit
  = link_to 'Cancel', root_path

app/views/products/_review.html.slim
= bootstrap_form_for ([product, review]) do |f|
  .row
    .col-sm-8
      = f.text_area :msg, rows: 5, placeholder: "write some...", label: "Write Review"
      = f.submit "Submit"

app/views/products/edit.html.slim
= render 'form'

app/views/products/index.html.slim
p.lead List of products

- products.each do |product|
  ul.list-unstyled.ui-sortable
    li= link_to product.title, product_path(product)

app/views/products/show.html.slim
h2
  p
    = product.title
  = image_tag product.image.url(:default), class: 'picture'
p
  = product.description

hr
  h4
   p
    | Leave your feedback for this product

= render 'products/review'

h4 Feedbacks (#{reviews.count})

ul.list-unstyled.ui-sortable
  - reviews.each do |review|
    - if review.persisted?
      li= review.msg
      p
        | by #{review.user.email}
        - if user_signed_in? && current_user.admin?
          = link_to 'Delete', product_review_path(product, review), method: :delete, data: { confirm: 'A u sure?' },
                    class: 'btn-mini btn-danger'

- if user_signed_in? && current_user.admin?
  = link_to 'Edit', edit_product_path(product)
  | |
  = link_to 'Back', products_path
  | |
  = link_to 'Delete', product_path(product), method: :delete, data: { confirm: 'A u sure?' },
            class: 'btn-mini btn-danger'